name: Merge QA to Main
 
on:
  workflow_run:
    workflows:
      - Merge Development to QA
    types:
      - completed
 
permissions:
  contents: write
 
jobs:
  merge-qa-to-main:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout QA
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: qa
 
      - name: Merge QA into Main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
 
          git fetch origin
 
          git checkout main
          git pull origin main
 
          git merge origin/qa --no-edit
 
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git main
